app:
  port: 9001
  name: "API Gateway"
routes:
  - path: /api/v1/orders/
    host: http://localhost:8000
  - path: /api/v1/organizations/
    host: http://localhost:8001
  - path: /api/v1/users/
    host: http://localhost:8002
redis:
  host: localhost
  port: 6380
  db: 0
  password: ""